//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/fepriyadi/dev/android/office/mnc/digital/analytics/mobile-sdk/iospowerlytics/j2objc/java/Core.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Core")
#ifdef RESTRICT_Core
#define INCLUDE_ALL_Core 0
#else
#define INCLUDE_ALL_Core 1
#endif
#undef RESTRICT_Core

#if !defined (ComPowerAnalyticsCore_) && (INCLUDE_ALL_Core || defined(INCLUDE_ComPowerAnalyticsCore))
#define ComPowerAnalyticsCore_

@class JavaLangBoolean;
@class JavaLangException;
@class OrgJsonJSONArray;

@interface ComPowerAnalyticsCore : NSObject

#pragma mark Public

- (instancetype)init;

+ (OrgJsonJSONArray *)removeFromJsonArrayWithOrgJsonJSONArray:(OrgJsonJSONArray *)jsrc
                                                      withInt:(jint)index;

#pragma mark Protected

+ (void)dpWithNSString:(NSString *)s;

- (void)dryRun_WithBoolean:(jboolean)dryRun;

- (void)flushDataWithBoolean:(jboolean)retry
                 withBoolean:(jboolean)flushAll;

- (NSString *)getAppStringWithNSString:(NSString *)fname;

- (NSString *)getAppVersion;

- (NSString *)getDeviceDetails;

+ (void)peWithNSString:(NSString *)s
 withJavaLangException:(JavaLangException *)e;

- (jboolean)setAppStringWithNSString:(NSString *)fname
                        withNSString:(NSString *)s;

- (void)setClientStuffWithNSString:(NSString *)platform
                      withNSString:(NSString *)clientKey
                      withNSString:(NSString *)productDomain
                      withNSString:(NSString *)bundleId
                      withNSString:(NSString *)userID;

- (void)setEnvironmentProduction_WithBoolean:(jboolean)production;

- (void)setLastEnvironment;

- (void)setStagingUrl_WithNSString:(NSString *)stagingUrl;

- (void)videoAdAbr_WithInt:(jint)bitrate;

- (void)videoAdBuffer_;

- (void)videoAdClicked_WithNSString:(NSString *)tag;

- (void)videoAdComplete_WithNSString:(NSString *)tag;

- (void)videoAdError_WithNSString:(NSString *)tag
                     withNSString:(NSString *)msg;

- (void)videoAdLoad_WithNSString:(NSString *)tag;

- (void)videoAdPause_WithNSString:(NSString *)tag;

- (void)videoAdPlay_WithNSString:(NSString *)tag;

- (void)videoAdSkipped_WithNSString:(NSString *)tag;

- (void)videoAdUnload_;

- (void)videoAdVbr_WithInt:(jint)bitrate;

- (void)videoAttributes_WithNSString:(NSString *)attributes;

- (jboolean)videoBitrate_WithInt:(jint)audio
                         withInt:(jint)video;

- (jboolean)videoBuffer_;

- (void)videoComplete_;

- (jboolean)videoDuration_WithDouble:(jdouble)duration;

- (void)videoError_WithNSString:(NSString *)errorMessage;

- (void)videoLoad_WithNSString:(NSString *)videoCategories
                  withNSString:(NSString *)videoId
                  withNSString:(NSString *)videoName;

- (void)videoPause_;

- (JavaLangBoolean *)videoPause_WithNSString:(NSString *)videoName;

- (jboolean)videoPlay_;

- (jboolean)videoPlaying_WithDouble:(jdouble)position;

- (jboolean)videoSeek_WithDouble:(jdouble)position;

- (void)videoTags_WithNSString:(NSString *)tags;

- (void)videoUnload_;

- (JavaLangBoolean *)videoUnload_WithNSString:(NSString *)videoName;

@end

J2OBJC_EMPTY_STATIC_INIT(ComPowerAnalyticsCore)

inline NSString *ComPowerAnalyticsCore_get_sDUuid(void);
inline NSString *ComPowerAnalyticsCore_set_sDUuid(NSString *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ComPowerAnalyticsCore_sDUuid;
J2OBJC_STATIC_FIELD_OBJ(ComPowerAnalyticsCore, sDUuid, NSString *)

inline NSString *ComPowerAnalyticsCore_get_sClientKey(void);
inline NSString *ComPowerAnalyticsCore_set_sClientKey(NSString *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ComPowerAnalyticsCore_sClientKey;
J2OBJC_STATIC_FIELD_OBJ(ComPowerAnalyticsCore, sClientKey, NSString *)

inline NSString *ComPowerAnalyticsCore_get_sBundleId(void);
inline NSString *ComPowerAnalyticsCore_set_sBundleId(NSString *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ComPowerAnalyticsCore_sBundleId;
J2OBJC_STATIC_FIELD_OBJ(ComPowerAnalyticsCore, sBundleId, NSString *)

inline NSString *ComPowerAnalyticsCore_get_sPlatform(void);
inline NSString *ComPowerAnalyticsCore_set_sPlatform(NSString *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ComPowerAnalyticsCore_sPlatform;
J2OBJC_STATIC_FIELD_OBJ(ComPowerAnalyticsCore, sPlatform, NSString *)

inline jboolean ComPowerAnalyticsCore_get_bProduction(void);
inline jboolean ComPowerAnalyticsCore_set_bProduction(jboolean value);
inline jboolean *ComPowerAnalyticsCore_getRef_bProduction(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jboolean ComPowerAnalyticsCore_bProduction;
J2OBJC_STATIC_FIELD_PRIMITIVE(ComPowerAnalyticsCore, bProduction, jboolean)

inline jboolean ComPowerAnalyticsCore_get_bDryRun(void);
inline jboolean ComPowerAnalyticsCore_set_bDryRun(jboolean value);
inline jboolean *ComPowerAnalyticsCore_getRef_bDryRun(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jboolean ComPowerAnalyticsCore_bDryRun;
J2OBJC_STATIC_FIELD_PRIMITIVE(ComPowerAnalyticsCore, bDryRun, jboolean)

inline jboolean ComPowerAnalyticsCore_get_bUsingLastSessId(void);
inline jboolean ComPowerAnalyticsCore_set_bUsingLastSessId(jboolean value);
inline jboolean *ComPowerAnalyticsCore_getRef_bUsingLastSessId(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jboolean ComPowerAnalyticsCore_bUsingLastSessId;
J2OBJC_STATIC_FIELD_PRIMITIVE(ComPowerAnalyticsCore, bUsingLastSessId, jboolean)

inline NSString *ComPowerAnalyticsCore_get_sProductDomain(void);
inline NSString *ComPowerAnalyticsCore_set_sProductDomain(NSString *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ComPowerAnalyticsCore_sProductDomain;
J2OBJC_STATIC_FIELD_OBJ(ComPowerAnalyticsCore, sProductDomain, NSString *)

inline NSString *ComPowerAnalyticsCore_get_sUserID(void);
inline NSString *ComPowerAnalyticsCore_set_sUserID(NSString *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ComPowerAnalyticsCore_sUserID;
J2OBJC_STATIC_FIELD_OBJ(ComPowerAnalyticsCore, sUserID, NSString *)

FOUNDATION_EXPORT void ComPowerAnalyticsCore_init(ComPowerAnalyticsCore *self);

FOUNDATION_EXPORT ComPowerAnalyticsCore *new_ComPowerAnalyticsCore_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComPowerAnalyticsCore *create_ComPowerAnalyticsCore_init(void);

FOUNDATION_EXPORT void ComPowerAnalyticsCore_dpWithNSString_(NSString *s);

FOUNDATION_EXPORT OrgJsonJSONArray *ComPowerAnalyticsCore_removeFromJsonArrayWithOrgJsonJSONArray_withInt_(OrgJsonJSONArray *jsrc, jint index);

FOUNDATION_EXPORT void ComPowerAnalyticsCore_peWithNSString_withJavaLangException_(NSString *s, JavaLangException *e);

J2OBJC_TYPE_LITERAL_HEADER(ComPowerAnalyticsCore)

#endif

#pragma pop_macro("INCLUDE_ALL_Core")
