//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/fep/dev/android/office/mnc/digital/analytics/mobile-sdk/ios/j2objc/java/Core.java
//

#include "Core.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "TTask.h"
#include "android/os/AsyncTask.h"
#include "java/io/InputStream.h"
#include "java/io/OutputStream.h"
#include "java/io/PrintStream.h"
#include "java/lang/Boolean.h"
#include "java/lang/Byte.h"
#include "java/lang/Exception.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/lang/StackTraceElement.h"
#include "java/lang/StringBuilder.h"
#include "java/lang/System.h"
#include "java/net/URL.h"
#include "java/net/URLConnection.h"
#include "java/security/MessageDigest.h"
#include "java/util/UUID.h"
#include "java/util/concurrent/TimeUnit.h"
#include "javax/net/ssl/HttpsURLConnection.h"
#include "org/json/JSONArray.h"
#include "org/json/JSONObject.h"

#if !__has_feature(objc_arc)
#error "Core must be compiled with ARC (-fobjc-arc)"
#endif

@interface Core ()

- (void)clearTmVars;

- (void)videoMeasure_WithNSString:(NSString *)sessid
                     withNSString:(NSString *)label
                     withNSString:(NSString *)value
                     withNSString:(NSString *)value2;

- (void)clearLoadData;

- (void)setLastTimeMillisEvent;

- (void)doFlushDataWithNSString:(NSString *)data;

- (NSString *)getSdkUserAgent;

- (NSString *)getHashWithNSString:(NSString *)s;

@end

inline jboolean Core_get_bOnFlushingData(void);
inline jboolean Core_set_bOnFlushingData(jboolean value);
inline jboolean *Core_getRef_bOnFlushingData(void);
static jboolean Core_bOnFlushingData = false;
J2OBJC_STATIC_FIELD_PRIMITIVE(Core, bOnFlushingData, jboolean)

inline jboolean Core_get_bForceDataFlush(void);
inline jboolean Core_set_bForceDataFlush(jboolean value);
inline jboolean *Core_getRef_bForceDataFlush(void);
static jboolean Core_bForceDataFlush = false;
J2OBJC_STATIC_FIELD_PRIMITIVE(Core, bForceDataFlush, jboolean)

inline NSString *Core_get_sUrlStaging(void);
inline NSString *Core_set_sUrlStaging(NSString *value);
static NSString *Core_sUrlStaging = @"https://analytic-ott.stg.mncanalytics.id";
J2OBJC_STATIC_FIELD_OBJ(Core, sUrlStaging, NSString *)

inline NSString *Core_get_sSdkVer(void);
static NSString *Core_sSdkVer = @"1.2.8";
J2OBJC_STATIC_FIELD_OBJ_FINAL(Core, sSdkVer, NSString *)

inline jint Core_get_nMaxIndexToFlush(void);
#define Core_nMaxIndexToFlush 16
J2OBJC_STATIC_FIELD_CONSTANT(Core, nMaxIndexToFlush, jint)

inline NSString *Core_get_sFnameStore(void);
static NSString *Core_sFnameStore = @"bW5jX2RpZ2l0YWxfYW5hbHl0aWNz";
J2OBJC_STATIC_FIELD_OBJ_FINAL(Core, sFnameStore, NSString *)

inline NSString *Core_get_sFnameFlush(void);
static NSString *Core_sFnameFlush = @"X21uY19kaWdpdGFsX2FuYWx5dGljcw";
J2OBJC_STATIC_FIELD_OBJ_FINAL(Core, sFnameFlush, NSString *)

inline NSString *Core_get_sFnameDUuid(void);
static NSString *Core_sFnameDUuid = @"X21kYV91dWlkXw";
J2OBJC_STATIC_FIELD_OBJ_FINAL(Core, sFnameDUuid, NSString *)

inline NSString *Core_get_sFnameUserID(void);
static NSString *Core_sFnameUserID = @"X3VzZXJfdXVpZF8";
J2OBJC_STATIC_FIELD_OBJ_FINAL(Core, sFnameUserID, NSString *)

inline NSString *Core_get_sFnameClientKey(void);
static NSString *Core_sFnameClientKey = @"X2NsaWVudF9rZXlf";
J2OBJC_STATIC_FIELD_OBJ_FINAL(Core, sFnameClientKey, NSString *)

inline NSString *Core_get_sFnameProductDomain(void);
static NSString *Core_sFnameProductDomain = @"X3Byb2R1Y3RfZG9tYWluXw";
J2OBJC_STATIC_FIELD_OBJ_FINAL(Core, sFnameProductDomain, NSString *)

inline NSString *Core_get_sFnameBundleId(void);
static NSString *Core_sFnameBundleId = @"X2J1bmRsZV9pZF8";
J2OBJC_STATIC_FIELD_OBJ_FINAL(Core, sFnameBundleId, NSString *)

inline NSString *Core_get_sFnameIsProduction(void);
static NSString *Core_sFnameIsProduction = @"X2lzX3Byb2R1Y3Rpb25f";
J2OBJC_STATIC_FIELD_OBJ_FINAL(Core, sFnameIsProduction, NSString *)

inline NSString *Core_get_sFnameVideoSessionId(void);
static NSString *Core_sFnameVideoSessionId = @"X3ZpZGVvX3Nlc3Npb25faWRf";
J2OBJC_STATIC_FIELD_OBJ_FINAL(Core, sFnameVideoSessionId, NSString *)

inline NSString *Core_get_sFnameVideoCtgIdName(void);
static NSString *Core_sFnameVideoCtgIdName = @"X3ZpZGVvX2N0Z19pZF9uYW1lXw";
J2OBJC_STATIC_FIELD_OBJ_FINAL(Core, sFnameVideoCtgIdName, NSString *)

inline NSString *Core_get_sFnameVideoAttributes(void);
static NSString *Core_sFnameVideoAttributes = @"X3ZpZGVvX2F0dHJpYnV0ZXNf";
J2OBJC_STATIC_FIELD_OBJ_FINAL(Core, sFnameVideoAttributes, NSString *)

inline NSString *Core_get_sFnameVideoTags(void);
static NSString *Core_sFnameVideoTags = @"X3ZpZGVvX3RhZ3Nf";
J2OBJC_STATIC_FIELD_OBJ_FINAL(Core, sFnameVideoTags, NSString *)

inline NSString *Core_get_sFnameLastTsEvent(void);
static NSString *Core_sFnameLastTsEvent = @"X2xhc3RfdHNfZXZlbnRf";
J2OBJC_STATIC_FIELD_OBJ_FINAL(Core, sFnameLastTsEvent, NSString *)

inline NSString *Core_get_sFnameFlushState(void);
static NSString *Core_sFnameFlushState = @"X2FpetYoeFpYdHrd";
J2OBJC_STATIC_FIELD_OBJ_FINAL(Core, sFnameFlushState, NSString *)

inline NSString *Core_get_sVideoMeasureSessionId(void);
inline NSString *Core_set_sVideoMeasureSessionId(NSString *value);
static NSString *Core_sVideoMeasureSessionId = @"";
J2OBJC_STATIC_FIELD_OBJ(Core, sVideoMeasureSessionId, NSString *)

inline NSString *Core_get_sHashVideoCtgIdName(void);
inline NSString *Core_set_sHashVideoCtgIdName(NSString *value);
static NSString *Core_sHashVideoCtgIdName = @"";
J2OBJC_STATIC_FIELD_OBJ(Core, sHashVideoCtgIdName, NSString *)

inline NSString *Core_get_sHashVideoAttributes(void);
inline NSString *Core_set_sHashVideoAttributes(NSString *value);
static NSString *Core_sHashVideoAttributes = @"";
J2OBJC_STATIC_FIELD_OBJ(Core, sHashVideoAttributes, NSString *)

inline NSString *Core_get_sHashVideoTags(void);
inline NSString *Core_set_sHashVideoTags(NSString *value);
static NSString *Core_sHashVideoTags = @"";
J2OBJC_STATIC_FIELD_OBJ(Core, sHashVideoTags, NSString *)

inline jdouble Core_get_fLastVideoDuration(void);
inline jdouble Core_set_fLastVideoDuration(jdouble value);
inline jdouble *Core_getRef_fLastVideoDuration(void);
static jdouble Core_fLastVideoDuration = 0.0;
J2OBJC_STATIC_FIELD_PRIMITIVE(Core, fLastVideoDuration, jdouble)

inline jint Core_get_nVideoPlayTm(void);
inline jint Core_set_nVideoPlayTm(jint value);
inline jint *Core_getRef_nVideoPlayTm(void);
static jint Core_nVideoPlayTm = 0;
J2OBJC_STATIC_FIELD_PRIMITIVE(Core, nVideoPlayTm, jint)

inline jint Core_get_nVideoPlayingTm(void);
inline jint Core_set_nVideoPlayingTm(jint value);
inline jint *Core_getRef_nVideoPlayingTm(void);
static jint Core_nVideoPlayingTm = 0;
J2OBJC_STATIC_FIELD_PRIMITIVE(Core, nVideoPlayingTm, jint)

inline jint Core_get_nVideoBufferTm(void);
inline jint Core_set_nVideoBufferTm(jint value);
inline jint *Core_getRef_nVideoBufferTm(void);
static jint Core_nVideoBufferTm = 0;
J2OBJC_STATIC_FIELD_PRIMITIVE(Core, nVideoBufferTm, jint)

inline jint Core_get_nVideoSeekTm(void);
inline jint Core_set_nVideoSeekTm(jint value);
inline jint *Core_getRef_nVideoSeekTm(void);
static jint Core_nVideoSeekTm = 0;
J2OBJC_STATIC_FIELD_PRIMITIVE(Core, nVideoSeekTm, jint)

inline jint Core_get_nVideoBitrateTm(void);
inline jint Core_set_nVideoBitrateTm(jint value);
inline jint *Core_getRef_nVideoBitrateTm(void);
static jint Core_nVideoBitrateTm = 0;
J2OBJC_STATIC_FIELD_PRIMITIVE(Core, nVideoBitrateTm, jint)

inline jint Core_get_nLastVideoBitrate(void);
inline jint Core_set_nLastVideoBitrate(jint value);
inline jint *Core_getRef_nLastVideoBitrate(void);
static jint Core_nLastVideoBitrate = 0;
J2OBJC_STATIC_FIELD_PRIMITIVE(Core, nLastVideoBitrate, jint)

inline jint Core_get_nLastAudioBitrate(void);
inline jint Core_set_nLastAudioBitrate(jint value);
inline jint *Core_getRef_nLastAudioBitrate(void);
static jint Core_nLastAudioBitrate = 0;
J2OBJC_STATIC_FIELD_PRIMITIVE(Core, nLastAudioBitrate, jint)

inline jlong Core_get_nLastVideoEventTm(void);
inline jlong Core_set_nLastVideoEventTm(jlong value);
inline jlong *Core_getRef_nLastVideoEventTm(void);
static jlong Core_nLastVideoEventTm = 0LL;
J2OBJC_STATIC_FIELD_PRIMITIVE(Core, nLastVideoEventTm, jlong)

__attribute__((unused)) static void Core_clearTmVars(Core *self);

__attribute__((unused)) static void Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(Core *self, NSString *sessid, NSString *label, NSString *value, NSString *value2);

__attribute__((unused)) static void Core_clearLoadData(Core *self);

__attribute__((unused)) static void Core_setLastTimeMillisEvent(Core *self);

__attribute__((unused)) static void Core_doFlushDataWithNSString_(Core *self, NSString *data);

__attribute__((unused)) static NSString *Core_getSdkUserAgent(Core *self);

__attribute__((unused)) static NSString *Core_getHashWithNSString_(Core *self, NSString *s);

@interface Core_AnalyticsHit : TTask {
 @public
  Core *this$0_;
  NSString *sData_;
}

- (instancetype)initWithCore:(Core *)outer$
                withNSString:(NSString *)data;

- (void)ttDone;

- (id)ttBackground;

@end

J2OBJC_EMPTY_STATIC_INIT(Core_AnalyticsHit)

J2OBJC_FIELD_SETTER(Core_AnalyticsHit, sData_, NSString *)

__attribute__((unused)) static void Core_AnalyticsHit_initWithCore_withNSString_(Core_AnalyticsHit *self, Core *outer$, NSString *data);

__attribute__((unused)) static Core_AnalyticsHit *new_Core_AnalyticsHit_initWithCore_withNSString_(Core *outer$, NSString *data) NS_RETURNS_RETAINED;

__attribute__((unused)) static Core_AnalyticsHit *create_Core_AnalyticsHit_initWithCore_withNSString_(Core *outer$, NSString *data);

J2OBJC_TYPE_LITERAL_HEADER(Core_AnalyticsHit)

NSString *Core_sDUuid = @"";
NSString *Core_sClientKey = @"";
NSString *Core_sBundleId = @"";
NSString *Core_sPlatform = @"";
jboolean Core_bProduction = false;
jboolean Core_bDryRun = false;
jboolean Core_bUsingLastSessId = false;
NSString *Core_sProductDomain = @"";
NSString *Core_sUserID = @"";

@implementation Core

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  Core_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)dpWithNSString:(NSString *)s {
  Core_dpWithNSString_(s);
}

- (NSString *)getDeviceDetails {
  return @"";
}

- (NSString *)getAppVersion {
  return @"";
}

- (NSString *)getAppStringWithNSString:(NSString *)fname {
  return nil;
}

- (jboolean)setAppStringWithNSString:(NSString *)fname
                        withNSString:(NSString *)s {
  return false;
}

- (void)setClientStuffWithNSString:(NSString *)platform
                      withNSString:(NSString *)clientKey
                      withNSString:(NSString *)productDomain
                      withNSString:(NSString *)bundleId
                      withNSString:(NSString *)userID {
  if (platform == nil || [platform java_isEmpty]) {
    Core_dpWithNSString_(@"setClientStuff: platform should not null or empty");
    return;
  }
  Core_sPlatform = platform;
  NSString *flustData = [self getAppStringWithNSString:Core_sFnameFlush];
  if (flustData == nil || [flustData java_isEmpty]) {
    [self setAppStringWithNSString:Core_sFnameFlushState withNSString:@"false"];
  }
  if (clientKey == nil || [clientKey java_isEmpty]) {
    if ([((NSString *) nil_chk(Core_sClientKey)) java_isEmpty]) {
      NSString *ck = [self getAppStringWithNSString:Core_sFnameClientKey];
      if (ck != nil && ![ck java_isEmpty]) {
        Core_sClientKey = ck;
      }
    }
  }
  else {
    Core_sClientKey = clientKey;
    [self setAppStringWithNSString:Core_sFnameClientKey withNSString:Core_sClientKey];
  }
  if (productDomain == nil || [productDomain java_isEmpty]) {
    if ([((NSString *) nil_chk(Core_sProductDomain)) java_isEmpty]) {
      NSString *pd = [self getAppStringWithNSString:Core_sFnameProductDomain];
      if (pd != nil && ![pd java_isEmpty]) {
        Core_sProductDomain = pd;
      }
    }
  }
  else {
    Core_sProductDomain = productDomain;
    [self setAppStringWithNSString:Core_sFnameProductDomain withNSString:Core_sProductDomain];
  }
  if (bundleId == nil || [bundleId java_isEmpty]) {
    if ([((NSString *) nil_chk(Core_sBundleId)) java_isEmpty]) {
      NSString *bid = [self getAppStringWithNSString:Core_sFnameBundleId];
      if (bid != nil && ![bid java_isEmpty]) {
        Core_sBundleId = bid;
      }
    }
  }
  else {
    Core_sBundleId = bundleId;
    [self setAppStringWithNSString:Core_sFnameBundleId withNSString:Core_sBundleId];
  }
  if (userID == nil || [userID java_isEmpty]) {
    if ([((NSString *) nil_chk(Core_sUserID)) java_isEmpty]) {
      Core_sUserID = [self getAppStringWithNSString:Core_sFnameUserID];
      if (Core_sUserID == nil || [Core_sUserID java_isEmpty]) {
        Core_sUserID = [((JavaUtilUUID *) nil_chk(JavaUtilUUID_randomUUID())) description];
        [self setAppStringWithNSString:Core_sFnameUserID withNSString:Core_sUserID];
      }
    }
  }
  else {
    Core_sUserID = userID;
    [self setAppStringWithNSString:Core_sFnameUserID withNSString:Core_sUserID];
  }
  if ([((NSString *) nil_chk(Core_sDUuid)) java_isEmpty]) {
    Core_sDUuid = [self getAppStringWithNSString:Core_sFnameDUuid];
    if (Core_sDUuid == nil || [Core_sDUuid java_isEmpty]) {
      Core_sDUuid = [((JavaUtilUUID *) nil_chk(JavaUtilUUID_randomUUID())) description];
      [self setAppStringWithNSString:Core_sFnameDUuid withNSString:Core_sDUuid];
    }
  }
}

- (void)dryRun_WithBoolean:(jboolean)dryRun {
  Core_bDryRun = dryRun;
}

- (void)setEnvironmentProduction_WithBoolean:(jboolean)production {
  Core_bProduction = production;
  [self setAppStringWithNSString:Core_sFnameIsProduction withNSString:JavaLangBoolean_toStringWithBoolean_(Core_bProduction)];
}

- (void)setStagingUrl_WithNSString:(NSString *)stagingUrl {
  Core_sUrlStaging = stagingUrl;
}

- (void)setLastEnvironment {
  NSString *bp = [self getAppStringWithNSString:Core_sFnameIsProduction];
  if (bp != nil && ![bp java_isEmpty]) {
    Core_bProduction = JavaLangBoolean_parseBooleanWithNSString_(bp);
  }
}

- (void)clearTmVars {
  Core_clearTmVars(self);
}

- (void)videoMeasure_WithNSString:(NSString *)sessid
                     withNSString:(NSString *)label
                     withNSString:(NSString *)value
                     withNSString:(NSString *)value2 {
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, sessid, label, value, value2);
}

- (void)videoLoad_WithNSString:(NSString *)videoCategories
                  withNSString:(NSString *)videoId
                  withNSString:(NSString *)videoName {
  if (videoCategories == nil || [videoCategories java_isEmpty]) {
    Core_dpWithNSString_(@"Video category should not empty");
    return;
  }
  if (videoId == nil || [videoId java_isEmpty]) {
    Core_dpWithNSString_(@"Video ID should not empty");
    return;
  }
  if (videoName == nil || [videoName java_isEmpty]) {
    Core_dpWithNSString_(@"Video name should not empty");
    return;
  }
  if ([((NSString *) nil_chk(Core_sUserID)) java_isEmpty]) {
    Core_dpWithNSString_(@"UserID should not empty");
    return;
  }
  Core_fLastVideoDuration = 0.0;
  Core_clearTmVars(self);
  if ([((NSString *) nil_chk(Core_sHashVideoCtgIdName)) java_isEmpty]) {
    NSString *lctgidnm = [self getAppStringWithNSString:Core_sFnameVideoCtgIdName];
    if (lctgidnm != nil && ![lctgidnm java_isEmpty]) {
      Core_sHashVideoCtgIdName = lctgidnm;
    }
  }
  jlong curtm = JavaLangSystem_currentTimeMillis();
  jlong ntm = [((JavaUtilConcurrentTimeUnit *) nil_chk(JreLoadEnum(JavaUtilConcurrentTimeUnit, MILLISECONDS))) toSecondsWithLong:curtm];
  if (![((NSString *) nil_chk(Core_sHashVideoCtgIdName)) java_isEmpty]) {
    NSString *hctgidnm = Core_getHashWithNSString_(self, JreStrcat("$$", Core_sUserID, videoName));
    if ([((NSString *) nil_chk(Core_sHashVideoCtgIdName)) isEqual:hctgidnm]) {
      if (![((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
        Core_dpWithNSString_(JreStrcat("$J$J$J", @"exist sessid id with delta load = ", (ntm - Core_nLastVideoEventTm), @" || ntm ", ntm, @" || lastTmEvent = ", Core_nLastVideoEventTm));
        if ((ntm - Core_nLastVideoEventTm) < 30 && Core_nLastVideoEventTm != 0LL) {
          Core_dpWithNSString_(@"videoLoad_: Using last session ID");
          Core_bUsingLastSessId = true;
          return;
        }
        else {
          Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"x-unload", nil, nil);
          Core_clearLoadData(self);
        }
      }
      else {
        NSString *lsessid = [self getAppStringWithNSString:Core_sFnameVideoSessionId];
        if (lsessid != nil && ![lsessid java_isEmpty]) {
          Core_dpWithNSString_(JreStrcat("$J$J$J", @"exist sessid id with delta load = ", (ntm - Core_nLastVideoEventTm), @" || ntm ", ntm, @" || lastTmEvent = ", Core_nLastVideoEventTm));
          if ((ntm - Core_nLastVideoEventTm) < 30 && Core_nLastVideoEventTm != 0LL) {
            Core_dpWithNSString_(@"videoLoad_: Using last session ID");
            Core_bUsingLastSessId = true;
            return;
          }
          else {
            Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, lsessid, @"x-unload", nil, nil);
            Core_clearLoadData(self);
          }
        }
      }
    }
    else {
      NSString *lsessid = [self getAppStringWithNSString:Core_sFnameVideoSessionId];
      if (lsessid != nil && ![lsessid java_isEmpty]) {
        Core_dpWithNSString_(@"videoLoad_: Force unload last session ID");
        Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, lsessid, @"x-unload", nil, nil);
        Core_clearLoadData(self);
      }
    }
  }
  Core_dpWithNSString_(@"videoLoad_:3: Using new session ID");
  Core_bUsingLastSessId = false;
  jlong tsms = JavaLangSystem_currentTimeMillis();
  Core_sVideoMeasureSessionId = Core_getHashWithNSString_(self, JreStrcat("$J$$$$$", Core_sClientKey, tsms, Core_sUserID, Core_sDUuid, @"video_measure", videoId, videoName));
  [self setAppStringWithNSString:Core_sFnameVideoSessionId withNSString:Core_sVideoMeasureSessionId];
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"?geoip", nil, nil);
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"uadev", [self getDeviceDetails], nil);
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"userid", Core_sUserID, nil);
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"duuid", Core_sDUuid, nil);
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"load", nil, nil);
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"categories", videoCategories, nil);
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"id", videoId, nil);
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"name", videoName, nil);
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"sdk_ver", Core_sSdkVer, nil);
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"app_ver", [self getAppVersion], nil);
  Core_sHashVideoCtgIdName = Core_getHashWithNSString_(self, JreStrcat("$$", Core_sUserID, videoName));
  [self setAppStringWithNSString:Core_sFnameVideoCtgIdName withNSString:Core_sHashVideoCtgIdName];
}

- (void)videoAttributes_WithNSString:(NSString *)attributes {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoAttributes: video has not loaded yet");
    return;
  }
  if ([((NSString *) nil_chk(Core_sHashVideoAttributes)) java_isEmpty]) {
    NSString *lattr = [self getAppStringWithNSString:Core_sFnameVideoAttributes];
    if (lattr != nil && ![lattr java_isEmpty]) {
      Core_sHashVideoAttributes = lattr;
    }
  }
  if (![((NSString *) nil_chk(Core_sHashVideoAttributes)) java_isEmpty]) {
    NSString *hattr = Core_getHashWithNSString_(self, JreStrcat("$$", Core_sUserID, attributes));
    if ([((NSString *) nil_chk(Core_sHashVideoAttributes)) isEqual:hattr] && Core_bUsingLastSessId) {
      Core_dpWithNSString_(@"videoAttributes_: Using last attributes");
      return;
    }
  }
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"attributes", attributes, nil);
  Core_sHashVideoAttributes = Core_getHashWithNSString_(self, JreStrcat("$$", Core_sUserID, attributes));
  [self setAppStringWithNSString:Core_sFnameVideoAttributes withNSString:Core_sHashVideoAttributes];
}

- (void)videoTags_WithNSString:(NSString *)tags {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoTags: video has not loaded yet");
    return;
  }
  if ([((NSString *) nil_chk(Core_sHashVideoTags)) java_isEmpty]) {
    NSString *ltags = [self getAppStringWithNSString:Core_sFnameVideoTags];
    if (ltags != nil && ![ltags java_isEmpty]) {
      Core_sHashVideoTags = ltags;
    }
  }
  if (![((NSString *) nil_chk(Core_sHashVideoTags)) java_isEmpty]) {
    NSString *htags = Core_getHashWithNSString_(self, JreStrcat("$$", Core_sUserID, tags));
    if ([((NSString *) nil_chk(Core_sHashVideoTags)) isEqual:htags] && Core_bUsingLastSessId) {
      Core_dpWithNSString_(@"videoTags_: Using last tags");
      return;
    }
  }
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"tags", tags, nil);
  Core_sHashVideoTags = Core_getHashWithNSString_(self, JreStrcat("$$", Core_sUserID, tags));
  [self setAppStringWithNSString:Core_sFnameVideoTags withNSString:Core_sHashVideoTags];
}

- (jboolean)videoPlay_ {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoPlay: video has not loaded yet");
    return false;
  }
  jlong tsms = JavaLangSystem_currentTimeMillis();
  jint ntm = (jint) (JreLongDiv(tsms, 1000));
  if ((ntm - Core_nVideoPlayTm) < 10) {
    return false;
  }
  Core_clearTmVars(self);
  Core_nVideoPlayTm = ntm;
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"play", nil, nil);
  return true;
}

- (void)videoPause_ {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoPause: video has not loaded yet");
    return;
  }
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"pause", nil, nil);
}

- (JavaLangBoolean *)videoPause_WithNSString:(NSString *)videoName {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoPause: video has not loaded yet");
    return JavaLangBoolean_valueOfWithBoolean_(false);
  }
  if ([((NSString *) nil_chk(Core_sHashVideoCtgIdName)) java_isEmpty]) {
    NSString *lctgidnm = [self getAppStringWithNSString:Core_sFnameVideoCtgIdName];
    if (lctgidnm != nil && ![lctgidnm java_isEmpty]) {
      Core_sHashVideoCtgIdName = lctgidnm;
    }
  }
  NSString *hctgidnm = Core_getHashWithNSString_(self, JreStrcat("$$", Core_sUserID, videoName));
  if (![((NSString *) nil_chk(Core_sHashVideoCtgIdName)) java_isEmpty] && [((NSString *) nil_chk(Core_sHashVideoCtgIdName)) isEqual:hctgidnm]) {
    Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"pause", nil, nil);
    Core_dpWithNSString_(@"videoPause_: pause session successful");
    return JavaLangBoolean_valueOfWithBoolean_(true);
  }
  Core_dpWithNSString_(@"videoPause_: pause session abort. pause different content");
  return JavaLangBoolean_valueOfWithBoolean_(false);
}

- (void)videoComplete_ {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoComplete: video has not loaded yet");
    return;
  }
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"complete", nil, nil);
}

- (jboolean)videoBuffer_ {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoBuffer: video has not loaded yet");
    return false;
  }
  jlong tsms = JavaLangSystem_currentTimeMillis();
  jint ntm = (jint) (JreLongDiv(tsms, 1000));
  if ((ntm - Core_nVideoBufferTm) < 10) {
    return false;
  }
  Core_clearTmVars(self);
  Core_nVideoBufferTm = ntm;
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"buffer", nil, nil);
  return true;
}

- (jboolean)videoDuration_WithDouble:(jdouble)duration {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoDuration: video has not loaded yet");
    return false;
  }
  if (Core_fLastVideoDuration == duration) {
    return false;
  }
  Core_fLastVideoDuration = duration;
  jint intDuration = JreFpToInt(duration);
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"duration", NSString_java_valueOfInt_(intDuration), nil);
  return true;
}

- (jboolean)videoPlaying_WithDouble:(jdouble)position {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoPlaying: video has not loaded yet");
    return false;
  }
  jlong tsms = JavaLangSystem_currentTimeMillis();
  jint ntm = (jint) (JreLongDiv(tsms, 1000));
  if ((ntm - Core_nVideoPlayingTm) < 10) {
    return false;
  }
  Core_clearTmVars(self);
  Core_nVideoPlayingTm = ntm;
  jint intPos = JreFpToInt(position);
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"playing", nil, NSString_java_valueOfInt_(intPos));
  return true;
}

- (jboolean)videoBitrate_WithInt:(jint)audio
                         withInt:(jint)video {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoBitrate: video has not loaded yet");
    return false;
  }
  if (video < 1 && audio < 1) {
    return false;
  }
  else if (video < 0) video = 0;
  else if (audio < 0) audio = 0;
  jlong tsms = JavaLangSystem_currentTimeMillis();
  jint ntm = (jint) (JreLongDiv(tsms, 1000));
  if ((ntm - Core_nVideoBitrateTm) < 10) {
    return false;
  }
  Core_clearTmVars(self);
  Core_nVideoBitrateTm = ntm;
  jboolean shouldTrack = false;
  if (Core_nLastVideoBitrate != video) {
    Core_nLastVideoBitrate = video;
    shouldTrack = true;
  }
  if (Core_nLastAudioBitrate != audio) {
    Core_nLastAudioBitrate = audio;
    shouldTrack = true;
  }
  if (shouldTrack) {
    Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"bitrate", JavaLangInteger_toStringWithInt_(audio), JavaLangInteger_toStringWithInt_(video));
    return true;
  }
  return false;
}

- (jboolean)videoSeek_WithDouble:(jdouble)position {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoSeek: video has not loaded yet");
    return false;
  }
  jlong tsms = JavaLangSystem_currentTimeMillis();
  jint ntm = (jint) (JreLongDiv(tsms, 1000));
  if ((ntm - Core_nVideoSeekTm) < 10) {
    return false;
  }
  Core_clearTmVars(self);
  Core_nVideoSeekTm = ntm;
  jint intPos = JreFpToInt(position);
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"seek", nil, NSString_java_valueOfInt_(intPos));
  return true;
}

- (JavaLangBoolean *)videoUnload_WithNSString:(NSString *)videoName {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoUnload: video has not loaded yet");
    return JavaLangBoolean_valueOfWithBoolean_(false);
  }
  if ([((NSString *) nil_chk(Core_sHashVideoCtgIdName)) java_isEmpty]) {
    NSString *lctgidnm = [self getAppStringWithNSString:Core_sFnameVideoCtgIdName];
    if (lctgidnm != nil && ![lctgidnm java_isEmpty]) {
      Core_sHashVideoCtgIdName = lctgidnm;
    }
  }
  NSString *hctgidnm = Core_getHashWithNSString_(self, JreStrcat("$$", Core_sUserID, videoName));
  if (![((NSString *) nil_chk(Core_sHashVideoCtgIdName)) java_isEmpty] && [((NSString *) nil_chk(Core_sHashVideoCtgIdName)) isEqual:hctgidnm]) {
    Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"unload", nil, nil);
    Core_clearLoadData(self);
    Core_dpWithNSString_(@"videoUnload_: unload session successful");
    return JavaLangBoolean_valueOfWithBoolean_(true);
  }
  Core_dpWithNSString_(@"videoUnload_: unload session abort. unload different content");
  return JavaLangBoolean_valueOfWithBoolean_(false);
}

- (void)videoUnload_ {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoUnload: video has not loaded yet");
    return;
  }
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"unload", nil, nil);
  Core_clearLoadData(self);
}

- (void)videoError_WithNSString:(NSString *)errorMessage {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoError: video has not loaded yet");
    return;
  }
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"error", nil, errorMessage);
}

- (void)videoAdPlay_WithNSString:(NSString *)tag {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoAdPlay: video has not loaded yet");
    return;
  }
  NSString *ltag = @"";
  if (tag != nil) {
    ltag = tag;
  }
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"ad_play", nil, ltag);
}

- (void)videoAdPause_WithNSString:(NSString *)tag {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoAdPause: video has not loaded yet");
    return;
  }
  NSString *ltag = @"";
  if (tag != nil) {
    ltag = tag;
  }
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"ad_pause", nil, ltag);
}

- (void)videoAdError_WithNSString:(NSString *)tag
                     withNSString:(NSString *)msg {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoAdError: video has not loaded yet");
    return;
  }
  NSString *ltag = @"";
  if (tag != nil) {
    ltag = tag;
  }
  NSString *lmsg = @"";
  if (msg != nil) {
    lmsg = msg;
  }
  NSString *lprm = JreStrcat("$C$", ltag, '|', lmsg);
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"ad_error", nil, lprm);
}

- (void)videoAdComplete_WithNSString:(NSString *)tag {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoAdComplete: video has not loaded yet");
    return;
  }
  NSString *ltag = @"";
  if (tag != nil) {
    ltag = tag;
  }
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"ad_complete", nil, ltag);
}

- (void)videoAdClicked_WithNSString:(NSString *)tag {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoAdSkipped: video has not loaded yet");
    return;
  }
  NSString *ltag = @"";
  if (tag != nil) {
    ltag = tag;
  }
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"ad_clicked", nil, ltag);
}

- (void)videoAdSkipped_WithNSString:(NSString *)tag {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoAdSkipped: video has not loaded yet");
    return;
  }
  NSString *ltag = @"";
  if (tag != nil) {
    ltag = tag;
  }
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"ad_skipped", nil, ltag);
}

- (void)videoAdLoad_WithNSString:(NSString *)tag {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoAdLoad: video has not loaded yet");
    return;
  }
  NSString *ltag = @"";
  if (tag != nil) {
    ltag = tag;
  }
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"ad_load", nil, ltag);
}

- (void)videoAdUnload_ {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoAdFinish: video has not loaded yet");
    return;
  }
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"ad_unload", nil, nil);
}

- (void)videoAdBuffer_ {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoAdBuffer: video has not loaded yet");
    return;
  }
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"ad_buffer", nil, nil);
}

- (void)videoAdAbr_WithInt:(jint)bitrate {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoAdBuffer: video has not loaded yet");
    return;
  }
  if (bitrate < 0) bitrate = 0;
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"ad_abr", JavaLangInteger_toStringWithInt_(bitrate), nil);
}

- (void)videoAdVbr_WithInt:(jint)bitrate {
  if ([((NSString *) nil_chk(Core_sVideoMeasureSessionId)) java_isEmpty]) {
    Core_dpWithNSString_(@"videoAdBuffer: video has not loaded yet");
    return;
  }
  if (bitrate < 0) bitrate = 0;
  Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(self, Core_sVideoMeasureSessionId, @"ad_vbr", JavaLangInteger_toStringWithInt_(bitrate), nil);
}

- (void)flushDataWithBoolean:(jboolean)retry
                 withBoolean:(jboolean)flushAll {
  if (Core_bOnFlushingData) {
    if (!retry) {
      Core_dpWithNSString_(@"flushData: Force flush");
      Core_bForceDataFlush = true;
    }
    return;
  }
  if (JavaLangBoolean_parseBooleanWithNSString_([self getAppStringWithNSString:Core_sFnameFlushState])) {
    Core_doFlushDataWithNSString_(self, nil);
    return;
  }
  NSString *s = [self getAppStringWithNSString:Core_sFnameStore];
  if (s == nil || [s java_isEmpty]) {
    return;
  }
  NSString *t = @"";
  if (flushAll) {
    [self setAppStringWithNSString:Core_sFnameFlush withNSString:s];
    [self setAppStringWithNSString:Core_sFnameStore withNSString:t];
    Core_doFlushDataWithNSString_(self, s);
    return;
  }
  @try {
    OrgJsonJSONArray *jas = new_OrgJsonJSONArray_initWithNSString_(s);
    if ([jas length] < Core_nMaxIndexToFlush) {
      if (retry) {
        return;
      }
    }
    else {
      jint j = [jas length];
      OrgJsonJSONArray *jat = new_OrgJsonJSONArray_init();
      jint i;
      for (i = 0; i < j; i++) {
        (void) [jat putWithId:[jas getJSONObjectWithInt:i]];
      }
      for (i = 0; i < j; i++) {
        OrgJsonJSONArray *lja = Core_removeFromJsonArrayWithOrgJsonJSONArray_withInt_(jas, 0);
        if (lja != nil) {
          jas = lja;
        }
      }
      s = [jat description];
      t = [jas description];
    }
  }
  @catch (JavaLangException *e) {
    Core_dpWithNSString_(JreStrcat("$@", @"flushData:e: ", e));
  }
  [self setAppStringWithNSString:Core_sFnameFlush withNSString:s];
  [self setAppStringWithNSString:Core_sFnameStore withNSString:t];
  Core_doFlushDataWithNSString_(self, s);
}

+ (OrgJsonJSONArray *)removeFromJsonArrayWithOrgJsonJSONArray:(OrgJsonJSONArray *)jsrc
                                                      withInt:(jint)index {
  return Core_removeFromJsonArrayWithOrgJsonJSONArray_withInt_(jsrc, index);
}

- (void)clearLoadData {
  Core_clearLoadData(self);
}

- (void)setLastTimeMillisEvent {
  Core_setLastTimeMillisEvent(self);
}

- (void)doFlushDataWithNSString:(NSString *)data {
  Core_doFlushDataWithNSString_(self, data);
}

- (NSString *)getSdkUserAgent {
  return Core_getSdkUserAgent(self);
}

+ (void)peWithNSString:(NSString *)s
 withJavaLangException:(JavaLangException *)e {
  Core_peWithNSString_withJavaLangException_(s, e);
}

- (NSString *)getHashWithNSString:(NSString *)s {
  return Core_getHashWithNSString_(self, s);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0xc, 0, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x4, 2, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x4, 3, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 5, 6, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 7, 8, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 9, 8, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 10, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 11, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 13, 14, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 15, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 16, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaLangBoolean;", 0x4, 17, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x4, 18, 19, -1, -1, -1, -1 },
    { NULL, "Z", 0x4, 20, 19, -1, -1, -1, -1 },
    { NULL, "Z", 0x4, 21, 22, -1, -1, -1, -1 },
    { NULL, "Z", 0x4, 23, 19, -1, -1, -1, -1 },
    { NULL, "LJavaLangBoolean;", 0x4, 24, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 25, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 26, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 27, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 28, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 29, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 30, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 31, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 32, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 33, 34, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 35, 34, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 36, 37, -1, -1, -1, -1 },
    { NULL, "LOrgJsonJSONArray;", 0x9, 38, 39, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 40, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0xc, 41, 42, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x2, 43, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(dpWithNSString:);
  methods[2].selector = @selector(getDeviceDetails);
  methods[3].selector = @selector(getAppVersion);
  methods[4].selector = @selector(getAppStringWithNSString:);
  methods[5].selector = @selector(setAppStringWithNSString:withNSString:);
  methods[6].selector = @selector(setClientStuffWithNSString:withNSString:withNSString:withNSString:withNSString:);
  methods[7].selector = @selector(dryRun_WithBoolean:);
  methods[8].selector = @selector(setEnvironmentProduction_WithBoolean:);
  methods[9].selector = @selector(setStagingUrl_WithNSString:);
  methods[10].selector = @selector(setLastEnvironment);
  methods[11].selector = @selector(clearTmVars);
  methods[12].selector = @selector(videoMeasure_WithNSString:withNSString:withNSString:withNSString:);
  methods[13].selector = @selector(videoLoad_WithNSString:withNSString:withNSString:);
  methods[14].selector = @selector(videoAttributes_WithNSString:);
  methods[15].selector = @selector(videoTags_WithNSString:);
  methods[16].selector = @selector(videoPlay_);
  methods[17].selector = @selector(videoPause_);
  methods[18].selector = @selector(videoPause_WithNSString:);
  methods[19].selector = @selector(videoComplete_);
  methods[20].selector = @selector(videoBuffer_);
  methods[21].selector = @selector(videoDuration_WithDouble:);
  methods[22].selector = @selector(videoPlaying_WithDouble:);
  methods[23].selector = @selector(videoBitrate_WithInt:withInt:);
  methods[24].selector = @selector(videoSeek_WithDouble:);
  methods[25].selector = @selector(videoUnload_WithNSString:);
  methods[26].selector = @selector(videoUnload_);
  methods[27].selector = @selector(videoError_WithNSString:);
  methods[28].selector = @selector(videoAdPlay_WithNSString:);
  methods[29].selector = @selector(videoAdPause_WithNSString:);
  methods[30].selector = @selector(videoAdError_WithNSString:withNSString:);
  methods[31].selector = @selector(videoAdComplete_WithNSString:);
  methods[32].selector = @selector(videoAdClicked_WithNSString:);
  methods[33].selector = @selector(videoAdSkipped_WithNSString:);
  methods[34].selector = @selector(videoAdLoad_WithNSString:);
  methods[35].selector = @selector(videoAdUnload_);
  methods[36].selector = @selector(videoAdBuffer_);
  methods[37].selector = @selector(videoAdAbr_WithInt:);
  methods[38].selector = @selector(videoAdVbr_WithInt:);
  methods[39].selector = @selector(flushDataWithBoolean:withBoolean:);
  methods[40].selector = @selector(removeFromJsonArrayWithOrgJsonJSONArray:withInt:);
  methods[41].selector = @selector(clearLoadData);
  methods[42].selector = @selector(setLastTimeMillisEvent);
  methods[43].selector = @selector(doFlushDataWithNSString:);
  methods[44].selector = @selector(getSdkUserAgent);
  methods[45].selector = @selector(peWithNSString:withJavaLangException:);
  methods[46].selector = @selector(getHashWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "sDUuid", "LNSString;", .constantValue.asLong = 0, 0xc, -1, 44, -1, -1 },
    { "sClientKey", "LNSString;", .constantValue.asLong = 0, 0xc, -1, 45, -1, -1 },
    { "sBundleId", "LNSString;", .constantValue.asLong = 0, 0xc, -1, 46, -1, -1 },
    { "sPlatform", "LNSString;", .constantValue.asLong = 0, 0xc, -1, 47, -1, -1 },
    { "bProduction", "Z", .constantValue.asLong = 0, 0xc, -1, 48, -1, -1 },
    { "bDryRun", "Z", .constantValue.asLong = 0, 0xc, -1, 49, -1, -1 },
    { "bUsingLastSessId", "Z", .constantValue.asLong = 0, 0xc, -1, 50, -1, -1 },
    { "sProductDomain", "LNSString;", .constantValue.asLong = 0, 0xc, -1, 51, -1, -1 },
    { "sUserID", "LNSString;", .constantValue.asLong = 0, 0xc, -1, 52, -1, -1 },
    { "bOnFlushingData", "Z", .constantValue.asLong = 0, 0xa, -1, 53, -1, -1 },
    { "bForceDataFlush", "Z", .constantValue.asLong = 0, 0xa, -1, 54, -1, -1 },
    { "sUrlStaging", "LNSString;", .constantValue.asLong = 0, 0xa, -1, 55, -1, -1 },
    { "sSdkVer", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 56, -1, -1 },
    { "nMaxIndexToFlush", "I", .constantValue.asInt = Core_nMaxIndexToFlush, 0x1a, -1, -1, -1, -1 },
    { "sFnameStore", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 57, -1, -1 },
    { "sFnameFlush", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 58, -1, -1 },
    { "sFnameDUuid", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 59, -1, -1 },
    { "sFnameUserID", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 60, -1, -1 },
    { "sFnameClientKey", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 61, -1, -1 },
    { "sFnameProductDomain", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 62, -1, -1 },
    { "sFnameBundleId", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 63, -1, -1 },
    { "sFnameIsProduction", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 64, -1, -1 },
    { "sFnameVideoSessionId", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 65, -1, -1 },
    { "sFnameVideoCtgIdName", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 66, -1, -1 },
    { "sFnameVideoAttributes", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 67, -1, -1 },
    { "sFnameVideoTags", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 68, -1, -1 },
    { "sFnameLastTsEvent", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 69, -1, -1 },
    { "sFnameFlushState", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 70, -1, -1 },
    { "sVideoMeasureSessionId", "LNSString;", .constantValue.asLong = 0, 0xa, -1, 71, -1, -1 },
    { "sHashVideoCtgIdName", "LNSString;", .constantValue.asLong = 0, 0xa, -1, 72, -1, -1 },
    { "sHashVideoAttributes", "LNSString;", .constantValue.asLong = 0, 0xa, -1, 73, -1, -1 },
    { "sHashVideoTags", "LNSString;", .constantValue.asLong = 0, 0xa, -1, 74, -1, -1 },
    { "fLastVideoDuration", "D", .constantValue.asLong = 0, 0xa, -1, 75, -1, -1 },
    { "nVideoPlayTm", "I", .constantValue.asLong = 0, 0xa, -1, 76, -1, -1 },
    { "nVideoPlayingTm", "I", .constantValue.asLong = 0, 0xa, -1, 77, -1, -1 },
    { "nVideoBufferTm", "I", .constantValue.asLong = 0, 0xa, -1, 78, -1, -1 },
    { "nVideoSeekTm", "I", .constantValue.asLong = 0, 0xa, -1, 79, -1, -1 },
    { "nVideoBitrateTm", "I", .constantValue.asLong = 0, 0xa, -1, 80, -1, -1 },
    { "nLastVideoBitrate", "I", .constantValue.asLong = 0, 0xa, -1, 81, -1, -1 },
    { "nLastAudioBitrate", "I", .constantValue.asLong = 0, 0xa, -1, 82, -1, -1 },
    { "nLastVideoEventTm", "J", .constantValue.asLong = 0, 0xa, -1, 83, -1, -1 },
  };
  static const void *ptrTable[] = { "dp", "LNSString;", "getAppString", "setAppString", "LNSString;LNSString;", "setClientStuff", "LNSString;LNSString;LNSString;LNSString;LNSString;", "dryRun_", "Z", "setEnvironmentProduction_", "setStagingUrl_", "videoMeasure_", "LNSString;LNSString;LNSString;LNSString;", "videoLoad_", "LNSString;LNSString;LNSString;", "videoAttributes_", "videoTags_", "videoPause_", "videoDuration_", "D", "videoPlaying_", "videoBitrate_", "II", "videoSeek_", "videoUnload_", "videoError_", "videoAdPlay_", "videoAdPause_", "videoAdError_", "videoAdComplete_", "videoAdClicked_", "videoAdSkipped_", "videoAdLoad_", "videoAdAbr_", "I", "videoAdVbr_", "flushData", "ZZ", "removeFromJsonArray", "LOrgJsonJSONArray;I", "doFlushData", "pe", "LNSString;LJavaLangException;", "getHash", &Core_sDUuid, &Core_sClientKey, &Core_sBundleId, &Core_sPlatform, &Core_bProduction, &Core_bDryRun, &Core_bUsingLastSessId, &Core_sProductDomain, &Core_sUserID, &Core_bOnFlushingData, &Core_bForceDataFlush, &Core_sUrlStaging, &Core_sSdkVer, &Core_sFnameStore, &Core_sFnameFlush, &Core_sFnameDUuid, &Core_sFnameUserID, &Core_sFnameClientKey, &Core_sFnameProductDomain, &Core_sFnameBundleId, &Core_sFnameIsProduction, &Core_sFnameVideoSessionId, &Core_sFnameVideoCtgIdName, &Core_sFnameVideoAttributes, &Core_sFnameVideoTags, &Core_sFnameLastTsEvent, &Core_sFnameFlushState, &Core_sVideoMeasureSessionId, &Core_sHashVideoCtgIdName, &Core_sHashVideoAttributes, &Core_sHashVideoTags, &Core_fLastVideoDuration, &Core_nVideoPlayTm, &Core_nVideoPlayingTm, &Core_nVideoBufferTm, &Core_nVideoSeekTm, &Core_nVideoBitrateTm, &Core_nLastVideoBitrate, &Core_nLastAudioBitrate, &Core_nLastVideoEventTm, "LCore_AnalyticsHit;" };
  static const J2ObjcClassInfo _Core = { "Core", "com.mncdigital.analytics", ptrTable, methods, fields, 7, 0x1, 47, 41, -1, 84, -1, -1, -1 };
  return &_Core;
}

@end

void Core_init(Core *self) {
  NSObject_init(self);
}

Core *new_Core_init() {
  J2OBJC_NEW_IMPL(Core, init)
}

Core *create_Core_init() {
  J2OBJC_CREATE_IMPL(Core, init)
}

void Core_dpWithNSString_(NSString *s) {
  Core_initialize();
  if (!Core_bProduction) [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, out))) printlnWithNSString:JreStrcat("$$", @"MncDigitalAnalytics:MDACore:", s)];
}

void Core_clearTmVars(Core *self) {
  Core_nVideoPlayTm = Core_nVideoPlayingTm = Core_nVideoBufferTm = Core_nVideoSeekTm = Core_nVideoBitrateTm = 0;
}

void Core_videoMeasure_WithNSString_withNSString_withNSString_withNSString_(Core *self, NSString *sessid, NSString *label, NSString *value, NSString *value2) {
  Core_setLastTimeMillisEvent(self);
  jlong ntsms = JavaLangSystem_currentTimeMillis();
  NSString *stsms = JavaLangLong_toStringWithLong_(ntsms);
  [self flushDataWithBoolean:true withBoolean:false];
  NSString *s = [self getAppStringWithNSString:Core_sFnameStore];
  if (s == nil || [s java_isEmpty]) {
    s = @"[]";
  }
  jint maxlength = 0;
  NSString *sprefix = @"";
  @try {
    OrgJsonJSONObject *jo = new_OrgJsonJSONObject_init();
    (void) [jo putWithNSString:@"tsclient" withLong:ntsms];
    (void) [jo putWithNSString:@"sessid" withId:sessid];
    (void) [jo putWithNSString:@"group" withId:@"video_measure"];
    if ([((NSString *) nil_chk(label)) java_hasPrefix:@"x-"]) {
      NSString *sx = [self getAppStringWithNSString:Core_sFnameLastTsEvent];
      if (sx != nil && ![sx java_isEmpty]) {
        jlong nx = JavaLangLong_parseLongWithNSString_(sx);
        stsms = JavaLangLong_toStringWithLong_(nx + 5000);
      }
      label = [label java_substring:2];
    }
    (void) [jo putWithNSString:@"label" withId:label];
    NSString *lvalue = value == nil ? stsms : value;
    if (value2 != nil && ![value2 java_isEmpty]) {
      (void) JreStrAppendStrong(&lvalue, "$", (JreStrcat("C$", ',', value2)));
    }
    (void) [jo putWithNSString:@"value" withId:JreStrcat("$$", sprefix, lvalue)];
    OrgJsonJSONArray *ja = new_OrgJsonJSONArray_initWithNSString_(s);
    (void) [ja putWithId:jo];
    maxlength = [ja length];
    s = [ja description];
    [self setAppStringWithNSString:Core_sFnameLastTsEvent withNSString:stsms];
  }
  @catch (JavaLangException *e) {
    Core_dpWithNSString_(JreStrcat("$@", @"videoMeasure_:e: ", e));
  }
  [self setAppStringWithNSString:Core_sFnameStore withNSString:s];
  if (maxlength >= Core_nMaxIndexToFlush) {
    [self flushDataWithBoolean:false withBoolean:false];
  }
  if ([((NSString *) nil_chk(label)) isEqual:@"unload"] || [label isEqual:@"pause"] || [label isEqual:@"playing"] || [label java_contains:@"error"]) {
    [self flushDataWithBoolean:false withBoolean:true];
  }
}

OrgJsonJSONArray *Core_removeFromJsonArrayWithOrgJsonJSONArray_withInt_(OrgJsonJSONArray *jsrc, jint index) {
  Core_initialize();
  if (index < 0 || index >= [((OrgJsonJSONArray *) nil_chk(jsrc)) length]) {
    return nil;
  }
  OrgJsonJSONArray *jarr = nil;
  @try {
    jarr = new_OrgJsonJSONArray_init();
    for (jint i = 0, count = [((OrgJsonJSONArray *) nil_chk(jsrc)) length]; i < count; i++) {
      if (i != index) (void) [jarr putWithId:[jsrc getWithInt:i]];
    }
  }
  @catch (JavaLangException *e) {
    Core_peWithNSString_withJavaLangException_(@"removeFromJsonArray ", e);
  }
  return jarr;
}

void Core_clearLoadData(Core *self) {
  Core_sVideoMeasureSessionId = @"";
  [self setAppStringWithNSString:Core_sFnameVideoSessionId withNSString:Core_sVideoMeasureSessionId];
  Core_sHashVideoCtgIdName = @"";
  [self setAppStringWithNSString:Core_sFnameVideoCtgIdName withNSString:Core_sHashVideoCtgIdName];
  Core_sHashVideoAttributes = @"";
  [self setAppStringWithNSString:Core_sFnameVideoAttributes withNSString:Core_sHashVideoAttributes];
  Core_sHashVideoTags = @"";
  [self setAppStringWithNSString:Core_sFnameVideoTags withNSString:Core_sHashVideoTags];
}

void Core_setLastTimeMillisEvent(Core *self) {
  Core_nLastVideoEventTm = [((JavaUtilConcurrentTimeUnit *) nil_chk(JreLoadEnum(JavaUtilConcurrentTimeUnit, MILLISECONDS))) toSecondsWithLong:JavaLangSystem_currentTimeMillis()];
}

void Core_doFlushDataWithNSString_(Core *self, NSString *data) {
  if (data == nil || [data java_isEmpty]) {
    data = [self getAppStringWithNSString:Core_sFnameFlush];
    if (data == nil || [data java_isEmpty]) {
      return;
    }
  }
  Core_AnalyticsHit *ah = new_Core_AnalyticsHit_initWithCore_withNSString_(self, data);
  (void) [ah executeWithNSObjectArray:[IOSObjectArray newArrayWithLength:0 type:NSObject_class_()]];
}

NSString *Core_getSdkUserAgent(Core *self) {
  NSString *s = JreStrcat("$$$$$$", @"MncDigitalSdk: ", Core_sSdkVer, @", Platform: ", Core_sPlatform, @", BundleID: ", Core_sBundleId);
  return s;
}

void Core_peWithNSString_withJavaLangException_(NSString *s, JavaLangException *e) {
  Core_initialize();
  IOSObjectArray *stackTrace = [((JavaLangException *) nil_chk(e)) getStackTrace];
  {
    IOSObjectArray *a__ = stackTrace;
    JavaLangStackTraceElement * const *b__ = ((IOSObjectArray *) nil_chk(a__))->buffer_;
    JavaLangStackTraceElement * const *e__ = b__ + a__->size_;
    while (b__ < e__) {
      JavaLangStackTraceElement *element = *b__++;
      NSString *em = JreStrcat("$$$$$I$$C", @"Exception thrown from ", [((JavaLangStackTraceElement *) nil_chk(element)) getMethodName], @" in class ", [element getClassName], @" [on line number ", [element getLineNumber], @" of file ", [element getFileName], ']');
      Core_dpWithNSString_(JreStrcat("$$$", s, @": ", em));
    }
  }
}

NSString *Core_getHashWithNSString_(Core *self, NSString *s) {
  NSString *sres;
  @try {
    JavaSecurityMessageDigest *md = JavaSecurityMessageDigest_getInstanceWithNSString_(@"MD5");
    [((JavaSecurityMessageDigest *) nil_chk(md)) updateWithByteArray:[((NSString *) nil_chk(s)) java_getBytesWithCharsetName:@"UTF-8"]];
    IOSByteArray *digest = [md digest];
    JavaLangStringBuilder *hexString = new_JavaLangStringBuilder_init();
    {
      IOSByteArray *a__ = digest;
      jbyte const *b__ = ((IOSByteArray *) nil_chk(a__))->buffer_;
      jbyte const *e__ = b__ + a__->size_;
      while (b__ < e__) {
        jbyte b = *b__++;
        (void) [hexString appendWithNSString:NSString_java_formatWithNSString_withNSObjectArray_(@"%02x", [IOSObjectArray newArrayWithObjects:(id[]){ JavaLangByte_valueOfWithByte_(b) } count:1 type:NSObject_class_()])];
      }
    }
    sres = [hexString description];
  }
  @catch (JavaLangException *e) {
    Core_dpWithNSString_(JreStrcat("$@", @"getMD5:e: ", e));
    sres = [((JavaUtilUUID *) nil_chk(JavaUtilUUID_randomUUID())) description];
  }
  return sres;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(Core)

J2OBJC_NAME_MAPPING(Core, "com.mncdigital.analytics", "")

@implementation Core_AnalyticsHit

- (instancetype)initWithCore:(Core *)outer$
                withNSString:(NSString *)data {
  Core_AnalyticsHit_initWithCore_withNSString_(self, outer$, data);
  return self;
}

- (void)ttDone {
  *JreLoadStaticRef(Core, bOnFlushingData) = false;
  if (sData_ == nil) {
    [this$0_ setAppStringWithNSString:Core_sFnameFlush withNSString:@""];
    if (JreLoadStatic(Core, bForceDataFlush)) {
      *JreLoadStaticRef(Core, bForceDataFlush) = false;
      [this$0_ flushDataWithBoolean:true withBoolean:true];
    }
    return;
  }
  [this$0_ setAppStringWithNSString:Core_sFnameFlushState withNSString:@"true"];
}

- (id)ttBackground {
  if ([((NSString *) nil_chk(sData_)) isEqual:@"[]"]) {
    sData_ = nil;
    return nil;
  }
  NSString *mdaurl = JreLoadStatic(Core, bProduction) ? (JreStrcat("$$", @"https://", JreLoadStatic(Core, sProductDomain))) : JreLoadStatic(Core, sUrlStaging);
  NSString *urlTarget = JreStrcat("$$$", mdaurl, @"/api/", JreLoadStatic(Core, sClientKey));
  Core_dpWithNSString_(JreStrcat("$$$$", @"AnalyticsHit:UrlTarget: ", urlTarget, @", sData: ", sData_));
  if (JreLoadStatic(Core, bDryRun)) {
    sData_ = nil;
    return nil;
  }
  NSString *charset = @"UTF-8";
  JavaNetURL *url;
  JavaxNetSslHttpsURLConnection *urlconn;
  @try {
    url = new_JavaNetURL_initWithNSString_(urlTarget);
    urlconn = (JavaxNetSslHttpsURLConnection *) cast_chk([url openConnection], [JavaxNetSslHttpsURLConnection class]);
    [((JavaxNetSslHttpsURLConnection *) nil_chk(urlconn)) setConnectTimeoutWithInt:6000];
    [urlconn setReadTimeoutWithInt:6000];
    [urlconn setRequestPropertyWithNSString:@"User-Agent" withNSString:Core_getSdkUserAgent(this$0_)];
    [urlconn setRequestPropertyWithNSString:@"Origin" withNSString:JreStrcat("$$", mdaurl, @"/sdk/origin")];
    [urlconn setRequestPropertyWithNSString:@"Referer" withNSString:JreStrcat("$$", mdaurl, @"/sdk/referer")];
    [urlconn setRequestPropertyWithNSString:@"Content-Type" withNSString:@"text/plain"];
    [urlconn setDoOutputWithBoolean:true];
    [urlconn setUseCachesWithBoolean:false];
    [((JavaIoOutputStream *) nil_chk([urlconn getOutputStream])) writeWithByteArray:[((NSString *) nil_chk(sData_)) java_getBytesWithCharsetName:charset]];
    jint responseCode = [urlconn getResponseCode];
    jint x = responseCode - 199;
    JavaIoInputStream *is = x > 0 && x < 10 ? [urlconn getInputStream] : [urlconn getErrorStream];
    if (is == nil) {
      return nil;
    }
    Core_dpWithNSString_(@"AnalyticsHit:sData:sent");
    sData_ = nil;
  }
  @catch (JavaLangException *e) {
    Core_peWithNSString_withJavaLangException_(@"AnalyticsHit", e);
  }
  return nil;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x4, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x4, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithCore:withNSString:);
  methods[1].selector = @selector(ttDone);
  methods[2].selector = @selector(ttBackground);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LCore;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "sData_", "LNSString;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LCore;LNSString;", "LCore;" };
  static const J2ObjcClassInfo _Core_AnalyticsHit = { "AnalyticsHit", "com.mncdigital.analytics", ptrTable, methods, fields, 7, 0x2, 3, 2, 1, -1, -1, -1, -1 };
  return &_Core_AnalyticsHit;
}

@end

void Core_AnalyticsHit_initWithCore_withNSString_(Core_AnalyticsHit *self, Core *outer$, NSString *data) {
  self->this$0_ = outer$;
  TTask_init(self);
  self->sData_ = data;
  *JreLoadStaticRef(Core, bOnFlushingData) = true;
  [outer$ setAppStringWithNSString:Core_sFnameFlushState withNSString:@"false"];
}

Core_AnalyticsHit *new_Core_AnalyticsHit_initWithCore_withNSString_(Core *outer$, NSString *data) {
  J2OBJC_NEW_IMPL(Core_AnalyticsHit, initWithCore_withNSString_, outer$, data)
}

Core_AnalyticsHit *create_Core_AnalyticsHit_initWithCore_withNSString_(Core *outer$, NSString *data) {
  J2OBJC_CREATE_IMPL(Core_AnalyticsHit, initWithCore_withNSString_, outer$, data)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(Core_AnalyticsHit)
