//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/fep/dev/android/office/mnc/digital/analytics/mobile-sdk/ios/j2objc/java/TTask.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "TTask.h"
#include "android/os/AsyncTask.h"
#include "java/lang/Exception.h"

#if !__has_feature(objc_arc)
#error "TTask must be compiled with ARC (-fobjc-arc)"
#endif

@implementation TTask

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  TTask_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)ttDone {
}

- (id)ttBackground {
  return nil;
}

- (void)ttDuringWithNSObjectArray:(IOSObjectArray *)objs {
}

- (void)ttUpdateWithNSObjectArray:(IOSObjectArray *)objs {
  [self publishProgressWithNSObjectArray:objs];
}

- (id)doInBackgroundWithNSObjectArray:(IOSObjectArray *)params {
  return [self ttBackground];
}

- (void)onPostExecuteWithId:(id)s {
  @try {
    [self ttDone];
  }
  @catch (JavaLangException *e) {
    [e printStackTrace];
  }
}

- (void)onProgressUpdateWithNSObjectArray:(IOSObjectArray *)objs {
  [self ttDuringWithNSObjectArray:objs];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x84, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x84, 2, 1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x84, 3, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x84, 6, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(ttDone);
  methods[2].selector = @selector(ttBackground);
  methods[3].selector = @selector(ttDuringWithNSObjectArray:);
  methods[4].selector = @selector(ttUpdateWithNSObjectArray:);
  methods[5].selector = @selector(doInBackgroundWithNSObjectArray:);
  methods[6].selector = @selector(onPostExecuteWithId:);
  methods[7].selector = @selector(onProgressUpdateWithNSObjectArray:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "ttDuring", "[LNSObject;", "ttUpdate", "doInBackground", "onPostExecute", "LNSObject;", "onProgressUpdate", "Landroid/os/AsyncTask<Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;>;" };
  static const J2ObjcClassInfo _TTask = { "TTask", "com.mncdigital.analytics", ptrTable, methods, NULL, 7, 0x1, 8, 0, -1, -1, -1, 7, -1 };
  return &_TTask;
}

@end

void TTask_init(TTask *self) {
  AndroidOsAsyncTask_init(self);
}

TTask *new_TTask_init() {
  J2OBJC_NEW_IMPL(TTask, init)
}

TTask *create_TTask_init() {
  J2OBJC_CREATE_IMPL(TTask, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(TTask)

J2OBJC_NAME_MAPPING(TTask, "com.mncdigital.analytics", "")
